### ISSUE TITLE
Make it do images too.

### ISSUE THREAD

**Issue by worthy7** [sb2702/free-ai-video-upscaler#1]
Can you make it do images, and can you implement a live zooming function so that has the users scrolls into the image, it automatically updates the resolution?

**Comment by sb2702** [comment]
Sorry for the delay here. You can already do images with the WebSR SDK, see [this API](https://github.com/sb2702/websr?tab=readme-ov-file#more-control)

While a live zooming solution seems out of scope for this particular project, the WebSR SDK should make it easier to do something like that.

I would caution that the WebSR SDK uses very light neural networks and the upscaling quality won't be as good as using a much more powerful AI Upscaling network. I made these networks very light to be able to handle video content, which needs to handle up to ~100k images / frames per hour of content
